hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 2000

server:
  port: 9090
spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
    discovery:
      instance-id: ${spring.application.name}:${server.port}
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - name: Hystrix
            args:
              name : default
              fallbackUri: forward:/cc-converter/fallback

      routes:
        - id: service1
          uri: lb://service1
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/(?<path>.*), /$\{path}

management:
  endpoint:
    gateway:
      enabled: true # default value
    web:
      exposure:
        include: gateway

logging.level.org.springframework.cloud.consul: DEBUG